In [13]:
import pandas as pd

In [14]:
# Caminho para o arquivo na camada Bronze
file_path = "../../data/raw_parquet/sih_rd_sp_2023_01.parquet"

#Lendo o arquivo
df = pd.read_parquet(file_path)

# Exibindo o tamanho do dataset
print(f"Total de linhas e colunas: {df.shape}\n")

Total de linhas e colunas: (210225, 113)

### Visão inicial do DF

In [15]:
# Mostrando as 5 primeiras linhas
display(df.head())

# Listando todas as colunas disponíveis
print("\nColunas disponíveis:")
print(list(df.columns))

,uf_zi,ano_cmpt,mes_cmpt,espec,cgc_hosp,n_aih,ident,cep,munic_res,nasc,...,diagsec9,tpdisec1,tpdisec2,tpdisec3,tpdisec4,tpdisec5,tpdisec6,tpdisec7,tpdisec8,tpdisec9
0,350000,2023,01,01,47969134000189,3523100253090,1,14408058,351620,19850831,...,,1,0,0,0,0,0,0,0,0
1,350000,2023,01,01,47969134000189,3523100253101,1,14600000,354940,19550421,...,,1,1,1,0,0,0,0,0,0
2,350000,2023,01,01,47969134000189,3523100253123,1,14420000,352370,19651011,...,,1,0,0,0,0,0,0,0,0
3,350000,2023,01,01,47969134000189,3523100253134,1,14401199,351620,19440126,...,,1,0,0,0,0,0,0,0,0
4,350000,2023,01,01,47969134000189,3523100255917,1,14402275,351620,19610407,...,,1,0,0,0,0,0,0,0,0

Colunas disponíveis:
['uf_zi', 'ano_cmpt', 'mes_cmpt', 'espec', 'cgc_hosp', 'n_aih', 'ident', 'cep', 'munic_res', 'nasc', 'sexo', 'uti_mes_in', 'uti_mes_an', 'uti_mes_al', 'uti_mes_to', 'marca_uti', 'uti_int_in', 'uti_int_an', 'uti_int_al', 'uti_int_to', 'diar_acom', 'qt_diarias', 'proc_solic', 'proc_rea', 'val_sh', 'val_sp', 'val_sadt', 'val_rn', 'val_acomp', 'val_ortp', 'val_sangue', 'val_sadtsr', 'val_transp', 'val_obsang', 'val_ped1ac', 'val_tot', 'val_uti', 'us_tot', 'dt_inter', 'dt_saida', 'diag_princ', 'diag_secun', 'cobranca', 'natureza', 'nat_jur', 'gestao', 'rubrica', 'ind_vdrl', 'munic_mov', 'cod_idade', 'idade', 'dias_perm', 'morte', 'nacional', 'num_proc', 'car_int', 'tot_pt_sp', 'cpf_aut', 'homonimo', 'num_filhos', 'instru', 'cid_notif', 'contracep1', 'contracep2', 'gestrisco', 'insc_pn', 'seq_aih5', 'cbor', 'cnaer', 'vincprev', 'gestor_cod', 'gestor_tp', 'gestor_cpf', 'gestor_dt', 'cnes', 'cnpj_mant', 'infehosp', 'cid_asso', 'cid_morte', 'complex', 'financ', 'faec_tp', 'regct', 'raca_cor', 'etnia', 'sequencia', 'remessa', 'aud_just', 'sis_just', 'val_sh_fed', 'val_sp_fed', 'val_sh_ges', 'val_sp_ges', 'val_uci', 'marca_uci', 'diagsec1', 'diagsec2', 'diagsec3', 'diagsec4', 'diagsec5', 'diagsec6', 'diagsec7', 'diagsec8', 'diagsec9', 'tpdisec1', 'tpdisec2', 'tpdisec3', 'tpdisec4', 'tpdisec5', 'tpdisec6', 'tpdisec7', 'tpdisec8', 'tpdisec9']

###  As 10 principais causas de internação em SP (01/2023)

In [18]:
top_doencas = df['diag_princ'].value_counts().head(10).reset_index()
top_doencas.columns = ['codigo_cid', 'total_internacoes']

print("--- Top 10 Causas de Internação (Geral) ---")
display(top_doencas)

--- Top 10 Causas de Internação (Geral) ---

  codigo_cid  total_internacoes
0       O800               8633
1       O809               3634
2       J189               3178
3       I64                3122
4       N390               3051
5       Z302               2941
6       I219               2652
7       I500               2211
8       A419               2073
9       J180               1956

#### Com base na Classificação Internacional de Doenças (CID-10), aqui está o significado de cada código listado na tabela:

#### O800 (O80.0): Parto normal (espontâneo).

#### O809 (O80.9): Parto único espontâneo, não especificado.

#### J189 (J18.9): Pneumonia, não especificada.

#### I64: Acidente vascular cerebral (AVC), não especificado como hemorrágico ou isquêmico.

#### N390 (N39.0): Infecção do trato urinário (ITU) de localização não especificada.

#### Z302 (Z30.2): Esterilização (frequentemente associado a procedimentos como laqueadura ou vasectomia).

#### I219 (I21.9): Infarto agudo do miocárdio (ataque cardíaco) não especificado.

#### I500 (I50.0): Insuficiência cardíaca congestiva.

#### A419 (A41.9): Septicemia (infecção generalizada grave) não especificada.

#### J180 (J18.0): Broncopneumonia não especificada.

### Foco do Projeto: Alergias e Asma

In [20]:

# =====================================================================
# 2. O Nosso Foco: Filtrando os casos de Alergia / Asma
# =====================================================================
# J30: Rinite / L20: Dermatite atópica / T78: Reações alérgicas / J45: Asma
cids_alergia = ('J30', 'L20', 'T78', 'J45')

# Usamos 'startswith' para capturar tanto o CID geral (J45) quanto os subtipos (J450, J451, etc.)
# Convertendo para string antes com .astype(str) por segurança
mascara_alergias = df['diag_princ'].astype(str).str.startswith(cids_alergia)

df_alergias = df[mascara_alergias]

print(f"Total de internações encontradas com os nossos CIDs: {len(df_alergias)}\n")

# Agrupando os casos de alergia encontrados
alergias_agrupadas = df_alergias['diag_princ'].value_counts().reset_index()
alergias_agrupadas.columns = ['codigo_cid_alergia', 'total_internacoes']
display(alergias_agrupadas)

Total de internações encontradas com os nossos CIDs: 916

   codigo_cid_alergia  total_internacoes
0                J459                733
1                J450                 47
2                J45                  46
3                J458                 29
4                L209                 15
5                T782                 12
6                J451                 10
7                L208                  7
8                T784                  4
9                T789                  4
10               T780                  3
11               T783                  2
12               L20                   1
13               T781                  1
14               L200                  1
15               J303                  1